### ISSUE TITLE
New Term: Digital Blackface

### ISSUE THREAD

**Issue by philherb** [selfdefined/web-app#180]
Digital Blackface is a form of appropriation where white and non-black individuals use memes featuring black people. This is a 21st century version of Black minstrelsy which was prevalent in the 19th and 20th centuries.

It can go further where entire online personas are created. These are easy to spot as they almost always use terms like "as a black woman..." and resort to stereotypes of speech and grammar.

Problem:
This type of action is another in a long history of dehumanizing black individuals into exaggerated versions of themselves, especially black women.

Here are two great articles about it:
[https://www.teenvogue.com/story/digital-blackface-reaction-gifs](https://www.teenvogue.com/story/digital-blackface-reaction-gifs)
"For while reaction GIFs can and do every feeling under the sun, white and nonblack users seem to especially prefer GIFs with black people when it comes to emitting their most exaggerated emotions. Extreme joy, annoyance, anger and occasions for drama and gossip are a magnet for images of black people, especially black femmes."

[https://www.theawl.com/2014/08/memes-and-misogynoir/](https://www.theawl.com/2014/08/memes-and-misogynoir/)
"On Twitter lie countless handles featuring a Black person’s image, run by users who are most assuredly not Black. These accounts, which often include a “ghetto” name — the formula prefix “La+” is a favored trope — are riddled with poor attempts at Black vernacular, and feature stereotypes from the minstrel stage."

Solution:
Find a white person who you identify with and use images of them instead
______
I am struggling to nail down appropriate definitions, but it feels like a term that would fit into the dictionary.

**Comment by tatianamac** [comment]
@philherb Rad! Thanks for submitting this! I think it's great. Typically our white supremacy tools follow a loose structure below. If any sections don't apply you can omit. Usually Issues and Impact are the most important.
```
[definition]
## Issues
## Impact
## Examples
## Notes
## What To Do (instead)
## Further Reading
```
From what you wrote, I think you have a lot of that skeleton filled out. A few notes:
- [ ] I'd add to this under examples that it might be good to include when non-Black folks use darker-skinned emojis.

Below, are you referencing troll accounts that parade as Black women? If so, it might be good?
>It can go further where entire online personas are created. These are easy to spot as they almost always use terms like "as a black woman..." and resort to stereotypes of speech and grammar.

I also might change that to "resort to incorrect and illegitimate use of African American Vernacular English (AAVE).

If you'd like to convert this into a .md file and open a PR, let me know and we can help. Otherwise, I'll mark it as "help wanted"

**Comment by philherb** [comment]
Yes, thanks for the help and suggestions. I will convert this to an .md file

**Comment by AutoSponge** [comment]
Maybe add a "see also" for Corporate Blackface aka performative allyship. Source: https://www.tanyavital.com/news/keep-the-corporate-black-face via Kim Crayton.

**Comment by ovlb** [comment]
The initial defintion was added by #196. 

@AutoSponge can you open a new PR with this addition?

**Comment by tatianamac** [comment]
I also might add that it should be its own definition because it's a whole other set, but we could interconnect them by making them "Related Terms" on both terms once it's added.
