### ISSUE TITLE
Suggestion: bloated

### ISSUE THREAD

**Issue by malchata** [selfdefined/web-app#189]
There's a word I see used often, especially in web performance literature, and that word is "bloated". I used to use this word quite frequently in my own performance articles, but have come to seriously consider whether it's a slur in the sense that it implies a body image that doesn't conform to societal expectations of being thin.

It's possible I could be wrong and this word may be overloaded with additional more innocuous meanings (such as stomach bloating/edema/other conditions), and like always, the context that it is used in can change its impact. Yet, when I see sentences like this:

> The amount of bytes sent by the average website has bloated from 1.5 MB to 1.75 MB

To me, this has taken on a connotation of "fattening" in web performance parlance, and it's a word I'm actively avoiding in my own writing, but I wanted to gauge if its inclusion in the dictionary would be helpful.

**Comment by tatianamac** [comment]
@malchata I did a little research on this and I don't think that it's fatmisic to say this. Bloatedness a medical term and AFAIK is agnostic of weight and doesn't necessarily imply anything about appearance either.

What I will say is if you ever feel uncertain using a term like this and are actively avoiding, that your instincts are probably in the right place. Other medically appropriative terms exist, so that you thought of this is net gain, I think in terms of learning.

I do think it's an opportunity to be more specific. Some immediate alternates:
- grown
- been padded
- inflated

I'm going to close this issue. I appreciate the dialogue!

**Comment by malchata** [comment]
Thanks for the thoughtful response, @tatianamac! For me, this word was sort of on the fence, but I can understand that doesn't warrant its inclusion in the dictionary. Thanks for the talk!
